% script to compute features for all intermediate data files:

% David Huberdeau, NTB lab

%% For VMA2 experiment:
% data_dir = {...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data',...
% '/gpfs/milgram/project/turk-browne/projects/vma_statlearning_iEEG/intermediate_data'};
%
% data_files = {...
%     'DG_vma_comb15.h5',...
%     'CF_vma_comb_short15.h5',...
%     'CH_vma_comb14_fix.h5',...
%     'WL_vma_comb14.h5',...
%     'DR_vma_comb15.h5',...
%     'DC_vma_comb15.h5',...
%     'PL_vma_comb15.h5',...
%     'RW_vma_comb15.h5',...
%     'MS_vma_comb15.h5',...
%     'DRJan_vma_comb15.h5'...
%   };
%
% label_files = {...
%     'DG_vma_comb15_labels.mat',...
%     'CF_vma_comb_short15_labels.mat',...
%     'CH_vma_comb14_fix_labels.mat',...
%     'WL_vma_comb14_labels.mat',...
%     'DR_vma_comb15_labels.mat',...
%     'DC_vma_comb15_labels.mat',...
%     'PL_vma_comb15_labels.mat',...
%     'RW_vma_comb15_labels.mat',...
%     'MS_vma_comb15_labels.mat',...
%     'DRJan_vma_comb15_labels.mat'...
% };

%% For VMA1 experiment:
data_dir = {...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data',...
'/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data'};

subject_list = {'LL', 'DO', 'JB', 'BP', 'VS', 'JK', 'LO', 'NH'};
data_files = {...
    'LL_vma_comb_precues.h5',...
    'DO_vma_comb_precues.h5',...
    'JB_vma_comb_precues.h5',...
    'BP_vma_comb_precues.h5',...
    'VS_vma_comb_precues.h5',...
    'JK_vma_comb_precues.h5',...
    'LO_vma_comb_precues.h5',...
    'NH_vma_comb_precues.h5',...
  };

label_files = {...
  'LL_precues_0.mat',...
  'DO_precues_0.mat',...
  'JB_precues_0.mat',...
  'BP_precues_0.mat',...
  'VS_precues_0.mat',...
  'JK_precues_0.mat',...
  'LO_precues_0.mat',...
  'NH_precues_0.mat',...
};

output_dir = '/gpfs/milgram/project/turk-browne/projects/vma_recall_iEEG/intermediate_data';

% loop through all files:
for i_sub = 1:length(data_files)
    % load the data from it's hdf5 format:
    [features, f_err] = compute_erp_feature(...
        [data_dir{i_sub}, filesep, data_files{i_sub}], [.25, .75]);

    % save data data features in matlab format (bc they are going to be
    % much smaller).
    save([output_dir, filesep, data_files{i_sub}(1:3), '_erp_data.mat'],...
        'features');
end
