% Convert the labels for vma2 data in the 'data' structure data.label from 
% being an nx1 cell to a 1xn cell, which is the format in the vma1
% experiment. 

data_dir = '/Users/david/Box Sync/projects/vma_ieeg_combined/intermediate_data';
in_files = {'CF_labels.mat',...
'CH_labels.mat',...
'DC_labels.mat',...
'DG_labels.mat',...
'DRJlabels.mat',...
'DR_labels.mat',...
'MS_labels.mat',...
'PL_labels.mat',...
'RW_labels.mat',...
'WL_labels.mat'...
};

out_files = {'CF_labels2.mat',...
'CH_labels2.mat',...
'DC_labels2.mat',...
'DG_labels2.mat',...
'DRJlabels2.mat',...
'DR_labels2.mat',...
'MS_labels2.mat',...
'PL_labels2.mat',...
'RW_labels2.mat',...
'WL_labels2.mat'...
};

for i_file = 1:length(in_files)
    load([data_dir, filesep, in_files{i_file}]);
    
    data1 = data;
    clear data;
    data = struct('label', {0}, 'fsample', 512, 'elec',...
        struct('pnt', [], 'label', []), 'cfg', struct('version', []));
    
    data.label = cell(1, length(data1.label));
    for i_ch = 1:length(data1.label)
        data.label{i_ch} = data1.label{i_ch};
    end
    
    save([data_dir, filesep, out_files{i_file}], 'data');
end

